feat: force appstore login before bootstrap, update secrets

diff --git a/.config/yadm/bootstrap b/.config/yadm/bootstrap
--- a/.config/yadm/bootstrap
+++ b/.config/yadm/bootstrap
@@ -1,5 +1,21 @@
 #!/bin/sh
 
+yes_or_no() {
+	while true; do
+		read -p "$* [y/n]: " yn
+		case $yn in
+		[Yy]*) return 0 ;;
+		[Nn]*)
+			echo "Aborted"
+			return 1
+			;;
+		esac
+	done
+}
+
+open -a "App Store"
+yes_or_no "Did you login to the App Store?" || exit 1
+
 echo "Decrypting secrets"
 yadm decrypt
 echo "Updating the yadm repo origin URL with ssh"
@@ -30,7 +46,7 @@ fi
 
 # Install AstroNVim if it's missing
 if [ ! -d "$HOME/.config/nvim" ]; then
-	echo "Installing AstroNVim"
+	echo "Installing AstroNvim"
 	git clone --depth 1 https://github.com/AstroNvim/AstroNvim ~/.config/nvim
 	git clone git@github.com:FiNEk/astro_nvim.git ~/.config/nvim/lua/user
 	nvim --headless -c 'quitall'
@@ -38,7 +54,7 @@ fi
 
 echo "Setup complete!"
 echo "Things to do:"
-echo "Login to Bitwarden"
 echo "Enable Brave Sync"
-echo "Login to Telegram"
-echo "Login to Spotify"
+echo "Login to everything"
+echo "OPTIONAL: Disable SIP for yabai"
+echo "https://github.com/koekeishiya/yabai/wiki/Disabling-System-Integrity-Protection"
